name: Speedle Plus CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: build-test
    steps:
    # resolve https://github.com/actions/virtual-environments/issues/798
    - name: bypass ubuntu DNS issue
      run: |
       sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    - uses: actions/checkout@v2
      name: Checkout code
      with:
        path: src/github.com/teramoby/speedle-plus
    - uses: actions/setup-go@v2
      name: Setup Golang env
      with:
        go-version: 1.19.x
    - name: Build and test
      working-directory: src/github.com/teramoby/speedle-plus
      run: |
        export GOPATH=${GITHUB_WORKSPACE}
        make build
        echo ${GITHUB_ACTOR}_${GITHUB_RUN_ID}
        sed -i "s/speedletest/${GITHUB_ACTOR}_${GITHUB_RUN_ID}/g" ./pkg/store/mongodb/mongoStoreConfig.json
        cat ./pkg/store/mongodb/mongoStoreConfig.json
        make speedleUnitTests
    - name: drop the database for this test
      run: |
        mongo "mongodb+srv://cluster0.wfhda.mongodb.net/${GITHUB_ACTOR}_${GITHUB_RUN_ID}" --username speedleplus --password Passw0rd <<EOF
        db.dropDatabase()
        EOF
        

